### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by NathanBnm** [volfpeter/timer#8]
Your app does not have any icon for now. It's always better to create your own identity with an attractive icon. I you need help some people can be referenced in this issue.

You should have an icon in these different sizes: 16, 24, 32, 64 and 128.

**Comment by NathanBnm** [comment]
I'm thinking about @Fatih20, maybe you can help @volfpeter to design something :smile:

**Comment by Fatih20** [comment]
I'll get on it.

**Comment by volfpeter** [comment]
@NathanBnm @Fatih20 Thanks a lot guys! I don't even know what to say. Let me know if you ever visit Budapest, I would be happy to buy you a couple of drinks and have a chat :)

**Comment by Fatih20** [comment]
Fun facts, you can already buy me a drink! Go to my liberapay link on my bio and consider tipping me once I get this done.
